# Use the official Python image from the Docker Hub
FROM python:3.12.7-bookworm

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

RUN apt-get update && apt-get install -y \
    python3-dev \
    python3-pip \
    build-essential \
    libpq-dev \
    postgresql-server-dev-all \
    python3-psycopg2 \
    && apt-get clean


# Install the dependencies
RUN pip install psycopg2-binary
RUN pip install psycopg2
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container
COPY . .

# Expose the port the app runs on
EXPOSE 5000

# Configuramos las variables de entorno para Flask
ENV FLASK_APP=main.py
ENV FLASK_ENV=development

# Define the command to run the application
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]