swagger: "2.0"
info:
  title: API de Gestión de Flota
  description: API para gestionar una flota de vehículos.
  version: 1.0.0
paths:
  /proveedores/:
    get:
      summary: Listar Proveedores
      description: Obtiene una lista de todos los proveedores registrados.
      responses:
        '202':
          description: Lista de repuestos.
          schema:
            type: array
            items:
              $ref: '#/definitions/ProveedorResponse'
    post:
      summary: Alta de Proveedor
      description: Registra un nuevo proveedor en el sistema.
      parameters:
        - in: body
          name: body
          description: Datos del nuevo proveedor.
          required: true
          schema:
            $ref: '#/definitions/ProveedorRequest'
      responses:
        '202':
          description: 'OK'

  /proveedores/{id}:
    put:
      summary: Actualizar Proveedor
      description: Actualiza la información de un proveedor existente por su ID.
      parameters:
        - in: path
          name: id
          required: true
          type: integer
        - in: body
          name: body
          description: Datos actualizados del proveedor.
          required: true
          schema:
            $ref: '#/definitions/ProveedorRequest'
      responses:
        '202':
          description: OK
        '404':
          description: Proveedor no encontrado.

    delete:
      summary: Baja de Proveedor
      description: Elimina un proveedor específico por su ID.
      parameters:
        - in: path
          name: id
          required: true
          type: integer
      responses:
        '202':
          description: OK
        '400':
          description: Proveedor no encontrado.

  /repuestos/:
    get:
      summary: Listar Repuestos
      description: Obtiene una lista de todos los repuestos registrados.
      responses:
        '202':
          description: Lista de repuestos.
          schema:
            type: array
            items:
              $ref: '#/definitions/RepuestoResponse'

    post:
      summary: Alta de Repuesto
      description: Registra un nuevo repuesto en el sistema.
      parameters:
        - in: body
          name: body
          description: Datos del nuevo repuesto.
          required: true
          schema:
            $ref: '#/definitions/RepuestoRequest'
      responses:
        '202':
          description: Repuesto creado exitosamente.
        '400':
          description: Error al registrar el repuesto.

  /repuestos/{id}:
    get:
      summary: Obtener Repuesto por ID
      description: Obtiene la información de un repuesto específico a través de su ID.
      parameters:
        - in: path
          name: id
          required: true
          type: integer
      responses:
        '202':
          description: Información del repuesto.
          schema:
            $ref: '#/definitions/RepuestoResponse'
        '404':
          description: Repuesto no encontrado.

    delete:
      summary: Baja de Repuesto
      description: Elimina un repuesto específico por su ID.
      parameters:
        - in: path
          name: id
          required: true
          type: integer
      responses:
        '202':
          description: OK
        '400':
          description: Repuesto no encontrado.

  /repuestos/delModelo/{id_modelo}:
    get:
      summary: Obtener Repuestos por Modelo
      description: Obtiene una lista de repuestos asociados a un modelo específico de vehículo.
      parameters:
        - in: path
          name: id_modelo
          description: ID del modelo de vehículo.
          required: true
          type: integer
      responses:
        '202':
          description: Lista de repuestos asociados al modelo.
          schema:
            type: array
            items:
              $ref: '#/definitions/RepuestoResponse'
        '404':
          description: Modelo no encontrado.

definitions:
  VehiculoRequest:
    type: object
    properties:
      id_modelo:
        type: integer
      matricula:
        type: string
    required:
      - id_modelo
      - matricula

  VehiculoResponse:
    type: object
    properties:
      id:
        type: integer
      matricula:
        type: string
      id_traccar:
        type: integer
        description: ID registrado en la API de geoposicionamiento.
      estado:
        type: string
      kilometraje:
        type: integer
      modelo:
        $ref: '#/definitions/ModeloVehiculoResponse'
      operador:
        $ref: '#/definitions/UsuarioResponse'

  RepuestoRequest:
    type: object
    properties:
      nombre:
        type: string
      stock:
        type: integer
      umbral_minimo:
        type: integer
        description: Cantidad mínima permitida en stock.
      umbral_maximo:
        type: integer
        description: Cantidad máxima permitida en stock.
    required:
      - nombre
      - stock
      - umbral_minimo
      - umbral_maximo

  RepuestoResponse:
    type: object
    properties:
      id:
        type: integer
      nombre:
        type: string
      stock:
        type: integer
      umbral_minimo:
        type: integer
      umbral_maximo:
        type: integer
      modelo_vehiculo:
        $ref: '#/definitions/ModeloVehiculoResponse'

  MarcaVehiculoRequest:
    type: object
    properties:
      nombre:
        type: string
      logo:
        type: string
    required:
      - nombre

  MarcaVehiculoResponse:
    type: object
    properties:
      id:
        type: integer
      nombre:
        type: string
      logo:
        type: string

  ModeloVehiculoRequest:
    type: object
    properties:
      id_marca_vehiculo:
        type: integer
      nombre:
        type: string
      litrosx100km:
        type: number
        format: float
        description: Consumo promedio de combustible en litros por cada 100 km.
      anio:
        type: integer
    required:
      - id_marca_vehiculo
      - nombre
      - litrosx100km

  ModeloVehiculoResponse:
    type: object
    properties:
      id:
        type: integer
      nombre:
        type: string
      litrosx100km:
        type: number
        format: float
        description: Consumo promedio de combustible en litros por cada 100 km.
      anio:
        type: integer
      marca_vehiculo:
        $ref: '#/definitions/MarcaVehiculoResponse'

  UsuarioRequest:
    type: object
    properties:
      nombre:
        type: string
      contrasena:
        type: string
      rol:
        type: string
    required:
      - nombre
      - contrasena
      - rol

  UsuarioResponse:
    type: object
    properties:
      id:
        type: integer
      nombre:
        type: string
      rol:
        type: string

  ProveedorRequest:
    type: object
    properties:
      nombre:
        type: string
      direccion:
        type: string
      telefono:
        type: string
      cuit:
        type: string

  ProveedorResponse:
    type: object
    properties:
      id:
        type: integer
      nombre:
        type: string
      direccion:
        type: string
      telefono:
        type: string
      cuit:
        type: string